// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinHaciendaDomain.DB;

#nullable disable

namespace MinHaciendaDomain.Migrations
{
    [DbContext(typeof(MinHaciendaContext))]
    [Migration("20241127184214_CrearBD")]
    partial class CrearBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsignacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("asignaciones");

                    b.HasData(
                        new
                        {
                            AsignacionId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 1,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 2,
                            Semestre = 5
                        },
                        new
                        {
                            AsignacionId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 3,
                            Semestre = 9
                        },
                        new
                        {
                            AsignacionId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 4,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            ProfesorId = 5,
                            Semestre = 2
                        },
                        new
                        {
                            AsignacionId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 6,
                            Semestre = 6
                        },
                        new
                        {
                            AsignacionId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 7,
                            Semestre = 4
                        },
                        new
                        {
                            AsignacionId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 8,
                            Semestre = 4
                        },
                        new
                        {
                            AsignacionId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 9,
                            Semestre = 5
                        },
                        new
                        {
                            AsignacionId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            ProfesorId = 10,
                            Semestre = 2
                        },
                        new
                        {
                            AsignacionId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 11,
                            Semestre = 5
                        },
                        new
                        {
                            AsignacionId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 12,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 13,
                            Semestre = 5
                        },
                        new
                        {
                            AsignacionId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            ProfesorId = 14,
                            Semestre = 7
                        },
                        new
                        {
                            AsignacionId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            ProfesorId = 15,
                            Semestre = 8
                        },
                        new
                        {
                            AsignacionId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            ProfesorId = 16,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            ProfesorId = 17,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            ProfesorId = 18,
                            Semestre = 1
                        },
                        new
                        {
                            AsignacionId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            ProfesorId = 19,
                            Semestre = 3
                        },
                        new
                        {
                            AsignacionId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            ProfesorId = 20,
                            Semestre = 4
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoId");

                    b.ToTable("cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Codigo = "POO",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Creditos = 25,
                            Nombre = "Programacion"
                        },
                        new
                        {
                            CursoId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Codigo = "ING",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Creditos = 15,
                            Nombre = "Ingles"
                        },
                        new
                        {
                            CursoId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Codigo = "CAL",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Creditos = 20,
                            Nombre = "Calculo II"
                        },
                        new
                        {
                            CursoId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Codigo = "ARQ",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Creditos = 25,
                            Nombre = "Arquitectura"
                        },
                        new
                        {
                            CursoId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Codigo = "SEG",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Creditos = 30,
                            Nombre = "Seguridad"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstudianteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId");

                    b.HasIndex("UserId");

                    b.ToTable("estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bednar",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Doris.Bednar@gmail.com",
                            FechaNacimiento = new DateTime(1963, 1, 9, 0, 9, 58, 755, DateTimeKind.Local).AddTicks(3270),
                            Genero = "F",
                            Nombre = "Doris",
                            UserId = 6
                        },
                        new
                        {
                            EstudianteId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wintheiser",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Allison_Wintheiser36@gmail.com",
                            FechaNacimiento = new DateTime(1978, 11, 11, 2, 40, 56, 756, DateTimeKind.Local).AddTicks(4432),
                            Genero = "F",
                            Nombre = "Allison",
                            UserId = 1
                        },
                        new
                        {
                            EstudianteId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Reynolds",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Pat.Reynolds@gmail.com",
                            FechaNacimiento = new DateTime(1968, 6, 1, 17, 4, 48, 709, DateTimeKind.Local).AddTicks(5802),
                            Genero = "F",
                            Nombre = "Pat",
                            UserId = 2
                        },
                        new
                        {
                            EstudianteId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Armstrong",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Bob_Armstrong31@yahoo.com",
                            FechaNacimiento = new DateTime(1994, 11, 4, 8, 21, 6, 900, DateTimeKind.Local).AddTicks(9304),
                            Genero = "F",
                            Nombre = "Bob",
                            UserId = 9
                        },
                        new
                        {
                            EstudianteId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kessler",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Janice83@yahoo.com",
                            FechaNacimiento = new DateTime(1975, 12, 29, 10, 30, 57, 153, DateTimeKind.Local).AddTicks(3813),
                            Genero = "F",
                            Nombre = "Janice",
                            UserId = 4
                        },
                        new
                        {
                            EstudianteId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rohan",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Aubrey.Rohan60@yahoo.com",
                            FechaNacimiento = new DateTime(1974, 11, 18, 23, 44, 26, 156, DateTimeKind.Local).AddTicks(3639),
                            Genero = "F",
                            Nombre = "Aubrey",
                            UserId = 5
                        },
                        new
                        {
                            EstudianteId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Jones",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Carroll78@yahoo.com",
                            FechaNacimiento = new DateTime(1960, 3, 26, 15, 45, 59, 349, DateTimeKind.Local).AddTicks(8566),
                            Genero = "F",
                            Nombre = "Carroll",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pfannerstill",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Dave.Pfannerstill@gmail.com",
                            FechaNacimiento = new DateTime(1977, 2, 5, 20, 12, 45, 601, DateTimeKind.Local).AddTicks(9146),
                            Genero = "F",
                            Nombre = "Dave",
                            UserId = 1
                        },
                        new
                        {
                            EstudianteId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Graham",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Aaron.Graham0@yahoo.com",
                            FechaNacimiento = new DateTime(1977, 2, 21, 20, 12, 10, 96, DateTimeKind.Local).AddTicks(5362),
                            Genero = "F",
                            Nombre = "Aaron",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rice",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Josephine51@hotmail.com",
                            FechaNacimiento = new DateTime(2004, 1, 21, 22, 31, 10, 730, DateTimeKind.Local).AddTicks(2510),
                            Genero = "F",
                            Nombre = "Josephine",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Parisian",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Amber41@yahoo.com",
                            FechaNacimiento = new DateTime(1980, 11, 20, 9, 17, 33, 434, DateTimeKind.Local).AddTicks(5868),
                            Genero = "F",
                            Nombre = "Amber",
                            UserId = 5
                        },
                        new
                        {
                            EstudianteId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cormier",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Helen_Cormier@yahoo.com",
                            FechaNacimiento = new DateTime(1963, 4, 7, 19, 53, 2, 601, DateTimeKind.Local).AddTicks(3647),
                            Genero = "F",
                            Nombre = "Helen",
                            UserId = 2
                        },
                        new
                        {
                            EstudianteId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Ryan",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Megan_Ryan21@hotmail.com",
                            FechaNacimiento = new DateTime(1996, 5, 14, 11, 22, 7, 533, DateTimeKind.Local).AddTicks(2506),
                            Genero = "F",
                            Nombre = "Megan",
                            UserId = 5
                        },
                        new
                        {
                            EstudianteId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rath",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Gary25@yahoo.com",
                            FechaNacimiento = new DateTime(1974, 10, 20, 15, 54, 11, 79, DateTimeKind.Local).AddTicks(5307),
                            Genero = "F",
                            Nombre = "Gary",
                            UserId = 4
                        },
                        new
                        {
                            EstudianteId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Feeney",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Julie_Feeney@yahoo.com",
                            FechaNacimiento = new DateTime(1965, 9, 9, 22, 8, 4, 77, DateTimeKind.Local).AddTicks(3242),
                            Genero = "F",
                            Nombre = "Julie",
                            UserId = 4
                        },
                        new
                        {
                            EstudianteId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wolff",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Kristopher.Wolff@hotmail.com",
                            FechaNacimiento = new DateTime(1980, 7, 30, 6, 7, 40, 673, DateTimeKind.Local).AddTicks(8693),
                            Genero = "F",
                            Nombre = "Kristopher",
                            UserId = 2
                        },
                        new
                        {
                            EstudianteId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Corwin",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Sally_Corwin86@yahoo.com",
                            FechaNacimiento = new DateTime(1993, 2, 5, 14, 23, 38, 134, DateTimeKind.Local).AddTicks(2904),
                            Genero = "F",
                            Nombre = "Sally",
                            UserId = 9
                        },
                        new
                        {
                            EstudianteId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Reichert",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Jeffrey21@gmail.com",
                            FechaNacimiento = new DateTime(1995, 5, 16, 21, 21, 42, 794, DateTimeKind.Local).AddTicks(8540),
                            Genero = "F",
                            Nombre = "Jeffrey",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Leffler",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Johnnie.Leffler87@gmail.com",
                            FechaNacimiento = new DateTime(1978, 3, 13, 2, 49, 51, 106, DateTimeKind.Local).AddTicks(9328),
                            Genero = "F",
                            Nombre = "Johnnie",
                            UserId = 2
                        },
                        new
                        {
                            EstudianteId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Swift",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Sherri_Swift@hotmail.com",
                            FechaNacimiento = new DateTime(1990, 8, 3, 22, 8, 19, 400, DateTimeKind.Local).AddTicks(6970),
                            Genero = "F",
                            Nombre = "Sherri",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 21,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Grimes",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Kenneth_Grimes@gmail.com",
                            FechaNacimiento = new DateTime(1987, 9, 2, 5, 3, 51, 74, DateTimeKind.Local).AddTicks(6917),
                            Genero = "F",
                            Nombre = "Kenneth",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 22,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Daugherty",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Woodrow.Daugherty@gmail.com",
                            FechaNacimiento = new DateTime(1987, 6, 2, 16, 16, 12, 257, DateTimeKind.Local).AddTicks(4107),
                            Genero = "F",
                            Nombre = "Woodrow",
                            UserId = 6
                        },
                        new
                        {
                            EstudianteId = 23,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wuckert",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Lucy.Wuckert13@hotmail.com",
                            FechaNacimiento = new DateTime(1980, 10, 31, 16, 37, 11, 481, DateTimeKind.Local).AddTicks(3173),
                            Genero = "F",
                            Nombre = "Lucy",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 24,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cummerata",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Clarence.Cummerata41@hotmail.com",
                            FechaNacimiento = new DateTime(1983, 8, 9, 14, 34, 22, 198, DateTimeKind.Local).AddTicks(2200),
                            Genero = "F",
                            Nombre = "Clarence",
                            UserId = 9
                        },
                        new
                        {
                            EstudianteId = 25,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Gulgowski",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Kara_Gulgowski@yahoo.com",
                            FechaNacimiento = new DateTime(1956, 10, 22, 22, 23, 37, 507, DateTimeKind.Local).AddTicks(5339),
                            Genero = "F",
                            Nombre = "Kara",
                            UserId = 3
                        },
                        new
                        {
                            EstudianteId = 26,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hills",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Kendra89@hotmail.com",
                            FechaNacimiento = new DateTime(1996, 11, 1, 20, 58, 9, 274, DateTimeKind.Local).AddTicks(3475),
                            Genero = "F",
                            Nombre = "Kendra",
                            UserId = 3
                        },
                        new
                        {
                            EstudianteId = 27,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Ernser",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Sylvester_Ernser@gmail.com",
                            FechaNacimiento = new DateTime(1956, 9, 6, 12, 22, 12, 153, DateTimeKind.Local).AddTicks(8021),
                            Genero = "F",
                            Nombre = "Sylvester",
                            UserId = 3
                        },
                        new
                        {
                            EstudianteId = 28,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schuster",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Chad73@yahoo.com",
                            FechaNacimiento = new DateTime(1964, 12, 26, 0, 24, 1, 771, DateTimeKind.Local).AddTicks(707),
                            Genero = "F",
                            Nombre = "Chad",
                            UserId = 8
                        },
                        new
                        {
                            EstudianteId = 29,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Zieme",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Hugo_Zieme45@gmail.com",
                            FechaNacimiento = new DateTime(2003, 5, 26, 9, 7, 58, 926, DateTimeKind.Local).AddTicks(1523),
                            Genero = "F",
                            Nombre = "Hugo",
                            UserId = 7
                        },
                        new
                        {
                            EstudianteId = 30,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Zemlak",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Email = "Joshua_Zemlak@hotmail.com",
                            FechaNacimiento = new DateTime(1983, 2, 1, 5, 35, 2, 265, DateTimeKind.Local).AddTicks(6648),
                            Genero = "F",
                            Nombre = "Joshua",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InscripcionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("InscripcionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("inscripciones");

                    b.HasData(
                        new
                        {
                            InscripcionId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 1,
                            FechaInscripcion = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 2,
                            FechaInscripcion = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 3,
                            FechaInscripcion = new DateTime(2020, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 4,
                            FechaInscripcion = new DateTime(2020, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 5,
                            FechaInscripcion = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 6,
                            FechaInscripcion = new DateTime(2020, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 7,
                            FechaInscripcion = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 8,
                            FechaInscripcion = new DateTime(2021, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 9,
                            FechaInscripcion = new DateTime(2022, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 10,
                            FechaInscripcion = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 11,
                            FechaInscripcion = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 12,
                            FechaInscripcion = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 13,
                            FechaInscripcion = new DateTime(2021, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 14,
                            FechaInscripcion = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 15,
                            FechaInscripcion = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 16,
                            FechaInscripcion = new DateTime(2020, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 17,
                            FechaInscripcion = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 18,
                            FechaInscripcion = new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 19,
                            FechaInscripcion = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 20,
                            FechaInscripcion = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 21,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 21,
                            FechaInscripcion = new DateTime(2020, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 22,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 22,
                            FechaInscripcion = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 23,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 23,
                            FechaInscripcion = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 24,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 24,
                            FechaInscripcion = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 25,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 25,
                            FechaInscripcion = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 26,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 2,
                            EstudianteId = 26,
                            FechaInscripcion = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 27,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 27,
                            FechaInscripcion = new DateTime(2020, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 28,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 1,
                            EstudianteId = 28,
                            FechaInscripcion = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 29,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 4,
                            EstudianteId = 29,
                            FechaInscripcion = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InscripcionId = 30,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            CursoId = 3,
                            EstudianteId = 30,
                            FechaInscripcion = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfesorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Heidenreich",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "suscipit",
                            Email = "Frederick.Heidenreich@yahoo.com",
                            Nombre = "Frederick"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Walter",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "molestiae",
                            Email = "Lucia40@gmail.com",
                            Nombre = "Lucia"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lubowitz",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptatibus",
                            Email = "Mike.Lubowitz@gmail.com",
                            Nombre = "Mike"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Windler",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "autem",
                            Email = "Linda_Windler@yahoo.com",
                            Nombre = "Linda"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pfannerstill",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "expedita",
                            Email = "Larry.Pfannerstill98@yahoo.com",
                            Nombre = "Larry"
                        },
                        new
                        {
                            ProfesorId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cartwright",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "autem",
                            Email = "Mercedes45@gmail.com",
                            Nombre = "Mercedes"
                        },
                        new
                        {
                            ProfesorId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Collier",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "consequuntur",
                            Email = "Sammy72@gmail.com",
                            Nombre = "Sammy"
                        },
                        new
                        {
                            ProfesorId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Runolfsson",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "dolorem",
                            Email = "Otis.Runolfsson@yahoo.com",
                            Nombre = "Otis"
                        },
                        new
                        {
                            ProfesorId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Fadel",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "sit",
                            Email = "Domingo_Fadel3@gmail.com",
                            Nombre = "Domingo"
                        },
                        new
                        {
                            ProfesorId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Jacobson",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "quo",
                            Email = "Erma39@gmail.com",
                            Nombre = "Erma"
                        },
                        new
                        {
                            ProfesorId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Parisian",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "dolor",
                            Email = "Patricia.Parisian@gmail.com",
                            Nombre = "Patricia"
                        },
                        new
                        {
                            ProfesorId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Berge",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "facilis",
                            Email = "Lance_Berge6@gmail.com",
                            Nombre = "Lance"
                        },
                        new
                        {
                            ProfesorId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Metz",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "et",
                            Email = "Ivan68@hotmail.com",
                            Nombre = "Ivan"
                        },
                        new
                        {
                            ProfesorId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kozey",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "non",
                            Email = "Emilio3@gmail.com",
                            Nombre = "Emilio"
                        },
                        new
                        {
                            ProfesorId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bechtelar",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "sint",
                            Email = "Judith_Bechtelar97@hotmail.com",
                            Nombre = "Judith"
                        },
                        new
                        {
                            ProfesorId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lesch",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "accusamus",
                            Email = "Nancy_Lesch@gmail.com",
                            Nombre = "Nancy"
                        },
                        new
                        {
                            ProfesorId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hegmann",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "porro",
                            Email = "Jeffery_Hegmann30@gmail.com",
                            Nombre = "Jeffery"
                        },
                        new
                        {
                            ProfesorId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wilkinson",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "soluta",
                            Email = "Vickie_Wilkinson@gmail.com",
                            Nombre = "Vickie"
                        },
                        new
                        {
                            ProfesorId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pfannerstill",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "aut",
                            Email = "Tyrone77@yahoo.com",
                            Nombre = "Tyrone"
                        },
                        new
                        {
                            ProfesorId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Torphy",
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            Departamento = "facilis",
                            Email = "Delia.Torphy43@hotmail.com",
                            Nombre = "Delia"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Sesion", b =>
                {
                    b.Property<Guid>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SesionID");

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expiration_Date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SesionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sesion");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre_apellido_280"
                        },
                        new
                        {
                            UserId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre.apellido_3"
                        },
                        new
                        {
                            UserId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre43"
                        },
                        new
                        {
                            UserId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre32"
                        },
                        new
                        {
                            UserId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre.apellido_6"
                        },
                        new
                        {
                            UserId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre.apellido_7"
                        },
                        new
                        {
                            UserId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre.apellido_8"
                        },
                        new
                        {
                            UserId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre_apellido_9"
                        },
                        new
                        {
                            UserId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre_apellido_1095"
                        },
                        new
                        {
                            UserId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creado = new DateTime(2024, 11, 27, 13, 42, 12, 982, DateTimeKind.Local).AddTicks(5204),
                            CreadoPor = "MinHacienda",
                            PasswordHash = "A94652AA97C7211B9ECA8F8B61E1A8A7",
                            Username = "nombre78"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Sesion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
