// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinHaciendaDomain.DB;

#nullable disable

namespace MinHaciendaDomain.Migrations
{
    [DbContext(typeof(MinHaciendaContext))]
    [Migration("20241121181716_CrearBD")]
    partial class CrearBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsignacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CursoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstudianteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InscripcionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("InscripcionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfesorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hermann",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "molestiae",
                            Email = "Patsy_Hermann@gmail.com",
                            Nombre = "Patsy"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rolfson",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "ullam",
                            Email = "Myron63@yahoo.com",
                            Nombre = "Myron"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Dicki",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptatem",
                            Email = "Jennifer.Dicki7@yahoo.com",
                            Nombre = "Jennifer"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Jakubowski",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "nemo",
                            Email = "Glenda.Jakubowski20@gmail.com",
                            Nombre = "Glenda"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Simonis",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "et",
                            Email = "Antonia.Simonis12@hotmail.com",
                            Nombre = "Antonia"
                        },
                        new
                        {
                            ProfesorId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Baumbach",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "commodi",
                            Email = "Terry_Baumbach@yahoo.com",
                            Nombre = "Terry"
                        },
                        new
                        {
                            ProfesorId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Howell",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "saepe",
                            Email = "Al.Howell61@gmail.com",
                            Nombre = "Al"
                        },
                        new
                        {
                            ProfesorId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schroeder",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "velit",
                            Email = "Lynne40@gmail.com",
                            Nombre = "Lynne"
                        },
                        new
                        {
                            ProfesorId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Murphy",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "perspiciatis",
                            Email = "Tanya_Murphy@gmail.com",
                            Nombre = "Tanya"
                        },
                        new
                        {
                            ProfesorId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Mueller",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "tempora",
                            Email = "Felicia_Mueller@gmail.com",
                            Nombre = "Felicia"
                        },
                        new
                        {
                            ProfesorId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Swaniawski",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "laudantium",
                            Email = "Theodore.Swaniawski89@hotmail.com",
                            Nombre = "Theodore"
                        },
                        new
                        {
                            ProfesorId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bednar",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "necessitatibus",
                            Email = "Sherman.Bednar@hotmail.com",
                            Nombre = "Sherman"
                        },
                        new
                        {
                            ProfesorId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Reichel",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "harum",
                            Email = "Van.Reichel@yahoo.com",
                            Nombre = "Van"
                        },
                        new
                        {
                            ProfesorId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bednar",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "nostrum",
                            Email = "Jerald.Bednar@hotmail.com",
                            Nombre = "Jerald"
                        },
                        new
                        {
                            ProfesorId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hirthe",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "consectetur",
                            Email = "Abraham_Hirthe2@gmail.com",
                            Nombre = "Abraham"
                        },
                        new
                        {
                            ProfesorId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Johnson",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "tempore",
                            Email = "Jeff_Johnson51@gmail.com",
                            Nombre = "Jeff"
                        },
                        new
                        {
                            ProfesorId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kihn",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "ut",
                            Email = "Isabel.Kihn34@gmail.com",
                            Nombre = "Isabel"
                        },
                        new
                        {
                            ProfesorId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hamill",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "consectetur",
                            Email = "Hazel_Hamill@yahoo.com",
                            Nombre = "Hazel"
                        },
                        new
                        {
                            ProfesorId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Beahan",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "aliquid",
                            Email = "Drew.Beahan@hotmail.com",
                            Nombre = "Drew"
                        },
                        new
                        {
                            ProfesorId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hayes",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "libero",
                            Email = "Sharon_Hayes@hotmail.com",
                            Nombre = "Sharon"
                        },
                        new
                        {
                            ProfesorId = 21,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pfeffer",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "consequatur",
                            Email = "Eric47@yahoo.com",
                            Nombre = "Eric"
                        },
                        new
                        {
                            ProfesorId = 22,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bruen",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "mollitia",
                            Email = "Angel.Bruen@hotmail.com",
                            Nombre = "Angel"
                        },
                        new
                        {
                            ProfesorId = 23,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Reichel",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "deleniti",
                            Email = "Steve.Reichel1@yahoo.com",
                            Nombre = "Steve"
                        },
                        new
                        {
                            ProfesorId = 24,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schinner",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "quisquam",
                            Email = "Pearl75@gmail.com",
                            Nombre = "Pearl"
                        },
                        new
                        {
                            ProfesorId = 25,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lesch",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "delectus",
                            Email = "Dominic.Lesch87@hotmail.com",
                            Nombre = "Dominic"
                        },
                        new
                        {
                            ProfesorId = 26,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wehner",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "praesentium",
                            Email = "Alonzo98@hotmail.com",
                            Nombre = "Alonzo"
                        },
                        new
                        {
                            ProfesorId = 27,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Blick",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "omnis",
                            Email = "Carol12@gmail.com",
                            Nombre = "Carol"
                        },
                        new
                        {
                            ProfesorId = 28,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Connelly",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "excepturi",
                            Email = "Herman.Connelly93@hotmail.com",
                            Nombre = "Herman"
                        },
                        new
                        {
                            ProfesorId = 29,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Brakus",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "soluta",
                            Email = "Alberto_Brakus92@gmail.com",
                            Nombre = "Alberto"
                        },
                        new
                        {
                            ProfesorId = 30,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hermann",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "sint",
                            Email = "Guadalupe.Hermann@hotmail.com",
                            Nombre = "Guadalupe"
                        },
                        new
                        {
                            ProfesorId = 31,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rolfson",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "cumque",
                            Email = "Norma.Rolfson38@yahoo.com",
                            Nombre = "Norma"
                        },
                        new
                        {
                            ProfesorId = 32,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hegmann",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptate",
                            Email = "Clara_Hegmann@hotmail.com",
                            Nombre = "Clara"
                        },
                        new
                        {
                            ProfesorId = 33,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Simonis",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptas",
                            Email = "Willis_Simonis59@yahoo.com",
                            Nombre = "Willis"
                        },
                        new
                        {
                            ProfesorId = 34,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Orn",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "quos",
                            Email = "Jasmine.Orn97@hotmail.com",
                            Nombre = "Jasmine"
                        },
                        new
                        {
                            ProfesorId = 35,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Weissnat",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptate",
                            Email = "Ernesto.Weissnat@gmail.com",
                            Nombre = "Ernesto"
                        },
                        new
                        {
                            ProfesorId = 36,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Waters",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "quas",
                            Email = "Alyssa31@gmail.com",
                            Nombre = "Alyssa"
                        },
                        new
                        {
                            ProfesorId = 37,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hammes",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "dolor",
                            Email = "Debra.Hammes32@gmail.com",
                            Nombre = "Debra"
                        },
                        new
                        {
                            ProfesorId = 38,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schinner",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "rerum",
                            Email = "Lula_Schinner1@yahoo.com",
                            Nombre = "Lula"
                        },
                        new
                        {
                            ProfesorId = 39,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Spinka",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "illo",
                            Email = "Isabel_Spinka@yahoo.com",
                            Nombre = "Isabel"
                        },
                        new
                        {
                            ProfesorId = 40,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Turner",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "animi",
                            Email = "Latoya.Turner@yahoo.com",
                            Nombre = "Latoya"
                        },
                        new
                        {
                            ProfesorId = 41,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Luettgen",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "autem",
                            Email = "Marsha_Luettgen@gmail.com",
                            Nombre = "Marsha"
                        },
                        new
                        {
                            ProfesorId = 42,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Quitzon",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "qui",
                            Email = "Elsa39@yahoo.com",
                            Nombre = "Elsa"
                        },
                        new
                        {
                            ProfesorId = 43,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Boyle",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "quidem",
                            Email = "Randal59@hotmail.com",
                            Nombre = "Randal"
                        },
                        new
                        {
                            ProfesorId = 44,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Doyle",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "modi",
                            Email = "Louise_Doyle@hotmail.com",
                            Nombre = "Louise"
                        },
                        new
                        {
                            ProfesorId = 45,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Block",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "harum",
                            Email = "Herbert_Block14@yahoo.com",
                            Nombre = "Herbert"
                        },
                        new
                        {
                            ProfesorId = 46,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cummerata",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "nostrum",
                            Email = "Bethany36@hotmail.com",
                            Nombre = "Bethany"
                        },
                        new
                        {
                            ProfesorId = 47,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Adams",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "ut",
                            Email = "Lela_Adams38@gmail.com",
                            Nombre = "Lela"
                        },
                        new
                        {
                            ProfesorId = 48,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Leannon",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "fugit",
                            Email = "Jamie18@hotmail.com",
                            Nombre = "Jamie"
                        },
                        new
                        {
                            ProfesorId = 49,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Farrell",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "ipsam",
                            Email = "Erick.Farrell@hotmail.com",
                            Nombre = "Erick"
                        },
                        new
                        {
                            ProfesorId = 50,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rogahn",
                            Creado = new DateTime(2024, 11, 21, 13, 17, 14, 995, DateTimeKind.Local).AddTicks(7397),
                            CreadoPor = "MinHacienda",
                            Departamento = "nisi",
                            Email = "Tim17@hotmail.com",
                            Nombre = "Tim"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
