// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinHaciendaDomain.DB;

#nullable disable

namespace MinHaciendaDomain.Migrations
{
    [DbContext(typeof(MinHaciendaContext))]
    [Migration("20241120194232_CrearBD")]
    partial class CrearBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsignacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CursoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstudianteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InscripcionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("InscripcionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfesorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bradtke",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "quia",
                            Email = "Marion.Bradtke59@gmail.com",
                            Nombre = "Marion"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rutherford",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "quaerat",
                            Email = "Delbert23@hotmail.com",
                            Nombre = "Delbert"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Moen",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "beatae",
                            Email = "Brooke.Moen9@yahoo.com",
                            Nombre = "Brooke"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Smith",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "cupiditate",
                            Email = "Teresa.Smith89@hotmail.com",
                            Nombre = "Teresa"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Gutmann",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "architecto",
                            Email = "Inez_Gutmann82@gmail.com",
                            Nombre = "Inez"
                        },
                        new
                        {
                            ProfesorId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Treutel",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "inventore",
                            Email = "Olivia23@yahoo.com",
                            Nombre = "Olivia"
                        },
                        new
                        {
                            ProfesorId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Senger",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "autem",
                            Email = "Lionel74@gmail.com",
                            Nombre = "Lionel"
                        },
                        new
                        {
                            ProfesorId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kihn",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "ea",
                            Email = "Erick34@yahoo.com",
                            Nombre = "Erick"
                        },
                        new
                        {
                            ProfesorId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cartwright",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "enim",
                            Email = "Kim_Cartwright@yahoo.com",
                            Nombre = "Kim"
                        },
                        new
                        {
                            ProfesorId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Dickinson",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "quis",
                            Email = "Pete_Dickinson@yahoo.com",
                            Nombre = "Pete"
                        },
                        new
                        {
                            ProfesorId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Braun",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "eum",
                            Email = "Lamar.Braun82@gmail.com",
                            Nombre = "Lamar"
                        },
                        new
                        {
                            ProfesorId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hand",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "laboriosam",
                            Email = "Taylor.Hand44@gmail.com",
                            Nombre = "Taylor"
                        },
                        new
                        {
                            ProfesorId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Reinger",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "esse",
                            Email = "Joel59@hotmail.com",
                            Nombre = "Joel"
                        },
                        new
                        {
                            ProfesorId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Feil",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "eum",
                            Email = "Toby_Feil@yahoo.com",
                            Nombre = "Toby"
                        },
                        new
                        {
                            ProfesorId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Howell",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "in",
                            Email = "Ebony.Howell@hotmail.com",
                            Nombre = "Ebony"
                        },
                        new
                        {
                            ProfesorId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Langworth",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "sed",
                            Email = "Randall.Langworth41@yahoo.com",
                            Nombre = "Randall"
                        },
                        new
                        {
                            ProfesorId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rohan",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "autem",
                            Email = "Paula23@hotmail.com",
                            Nombre = "Paula"
                        },
                        new
                        {
                            ProfesorId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hoppe",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "vel",
                            Email = "Stuart.Hoppe@gmail.com",
                            Nombre = "Stuart"
                        },
                        new
                        {
                            ProfesorId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Walter",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "placeat",
                            Email = "Rhonda82@yahoo.com",
                            Nombre = "Rhonda"
                        },
                        new
                        {
                            ProfesorId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Christiansen",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "nemo",
                            Email = "Josephine_Christiansen36@yahoo.com",
                            Nombre = "Josephine"
                        },
                        new
                        {
                            ProfesorId = 21,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hammes",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "eveniet",
                            Email = "Aubrey13@gmail.com",
                            Nombre = "Aubrey"
                        },
                        new
                        {
                            ProfesorId = 22,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schmitt",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "qui",
                            Email = "Lorena_Schmitt@yahoo.com",
                            Nombre = "Lorena"
                        },
                        new
                        {
                            ProfesorId = 23,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pfeffer",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptatem",
                            Email = "Camille.Pfeffer43@hotmail.com",
                            Nombre = "Camille"
                        },
                        new
                        {
                            ProfesorId = 24,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Dibbert",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "quo",
                            Email = "Ana48@yahoo.com",
                            Nombre = "Ana"
                        },
                        new
                        {
                            ProfesorId = 25,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Larkin",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "enim",
                            Email = "Bruce_Larkin61@gmail.com",
                            Nombre = "Bruce"
                        },
                        new
                        {
                            ProfesorId = 26,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wiza",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "debitis",
                            Email = "Irene_Wiza@gmail.com",
                            Nombre = "Irene"
                        },
                        new
                        {
                            ProfesorId = 27,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Farrell",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "veniam",
                            Email = "Gary_Farrell55@hotmail.com",
                            Nombre = "Gary"
                        },
                        new
                        {
                            ProfesorId = 28,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Raynor",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "omnis",
                            Email = "Jody88@gmail.com",
                            Nombre = "Jody"
                        },
                        new
                        {
                            ProfesorId = 29,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Jaskolski",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "dolores",
                            Email = "Patsy_Jaskolski@yahoo.com",
                            Nombre = "Patsy"
                        },
                        new
                        {
                            ProfesorId = 30,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schumm",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "recusandae",
                            Email = "Billie77@gmail.com",
                            Nombre = "Billie"
                        },
                        new
                        {
                            ProfesorId = 31,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kutch",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "iusto",
                            Email = "Ervin_Kutch4@yahoo.com",
                            Nombre = "Ervin"
                        },
                        new
                        {
                            ProfesorId = 32,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Parisian",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "sed",
                            Email = "Alice.Parisian61@hotmail.com",
                            Nombre = "Alice"
                        },
                        new
                        {
                            ProfesorId = 33,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Padberg",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "eum",
                            Email = "Sherri8@yahoo.com",
                            Nombre = "Sherri"
                        },
                        new
                        {
                            ProfesorId = 34,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Donnelly",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "saepe",
                            Email = "Mercedes48@hotmail.com",
                            Nombre = "Mercedes"
                        },
                        new
                        {
                            ProfesorId = 35,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Becker",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "est",
                            Email = "Jose54@hotmail.com",
                            Nombre = "Jose"
                        },
                        new
                        {
                            ProfesorId = 36,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Stanton",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "eum",
                            Email = "Todd76@hotmail.com",
                            Nombre = "Todd"
                        },
                        new
                        {
                            ProfesorId = 37,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Maggio",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "recusandae",
                            Email = "Peter.Maggio@hotmail.com",
                            Nombre = "Peter"
                        },
                        new
                        {
                            ProfesorId = 38,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Roberts",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "omnis",
                            Email = "Virginia_Roberts@hotmail.com",
                            Nombre = "Virginia"
                        },
                        new
                        {
                            ProfesorId = 39,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Donnelly",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "quia",
                            Email = "Wesley.Donnelly65@yahoo.com",
                            Nombre = "Wesley"
                        },
                        new
                        {
                            ProfesorId = 40,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Runte",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "consequatur",
                            Email = "Lena85@yahoo.com",
                            Nombre = "Lena"
                        },
                        new
                        {
                            ProfesorId = 41,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lockman",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "aut",
                            Email = "Ora_Lockman18@gmail.com",
                            Nombre = "Ora"
                        },
                        new
                        {
                            ProfesorId = 42,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wiza",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "unde",
                            Email = "Jenna59@yahoo.com",
                            Nombre = "Jenna"
                        },
                        new
                        {
                            ProfesorId = 43,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "D'Amore",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "iste",
                            Email = "Elisa37@gmail.com",
                            Nombre = "Elisa"
                        },
                        new
                        {
                            ProfesorId = 44,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Moen",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "et",
                            Email = "Zachary.Moen45@yahoo.com",
                            Nombre = "Zachary"
                        },
                        new
                        {
                            ProfesorId = 45,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hamill",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptatum",
                            Email = "Hilda_Hamill87@gmail.com",
                            Nombre = "Hilda"
                        },
                        new
                        {
                            ProfesorId = 46,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kilback",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "ut",
                            Email = "Kevin.Kilback@yahoo.com",
                            Nombre = "Kevin"
                        },
                        new
                        {
                            ProfesorId = 47,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Conn",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "necessitatibus",
                            Email = "Simon54@yahoo.com",
                            Nombre = "Simon"
                        },
                        new
                        {
                            ProfesorId = 48,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Jakubowski",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "nostrum",
                            Email = "Lynda_Jakubowski51@hotmail.com",
                            Nombre = "Lynda"
                        },
                        new
                        {
                            ProfesorId = 49,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lueilwitz",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "nam",
                            Email = "Cory_Lueilwitz@yahoo.com",
                            Nombre = "Cory"
                        },
                        new
                        {
                            ProfesorId = 50,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wunsch",
                            Creado = new DateTime(2024, 11, 20, 14, 42, 31, 220, DateTimeKind.Local).AddTicks(2573),
                            CreadoPor = "MinHacienda",
                            Departamento = "est",
                            Email = "Vincent_Wunsch23@yahoo.com",
                            Nombre = "Vincent"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Curso", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
