// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinHaciendaDomain.DB;

#nullable disable

namespace MinHaciendaDomain.Migrations
{
    [DbContext(typeof(MinHaciendaContext))]
    partial class MinHaciendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsignacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CursoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CursoId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstudianteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InscripcionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscripcionId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("InscripcionId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("inscripciones");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfesorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Upton",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "accusamus",
                            Email = "Damon_Upton68@yahoo.com",
                            Nombre = "Damon"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Fay",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptates",
                            Email = "Robin_Fay@gmail.com",
                            Nombre = "Robin"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Abernathy",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "accusamus",
                            Email = "Marlene72@yahoo.com",
                            Nombre = "Marlene"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "McCullough",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "quos",
                            Email = "George.McCullough@hotmail.com",
                            Nombre = "George"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Heathcote",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "nihil",
                            Email = "Viola77@hotmail.com",
                            Nombre = "Viola"
                        },
                        new
                        {
                            ProfesorId = 6,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bashirian",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "ea",
                            Email = "Patsy.Bashirian54@yahoo.com",
                            Nombre = "Patsy"
                        },
                        new
                        {
                            ProfesorId = 7,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Erdman",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "possimus",
                            Email = "Gilbert_Erdman@yahoo.com",
                            Nombre = "Gilbert"
                        },
                        new
                        {
                            ProfesorId = 8,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Mills",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "ut",
                            Email = "Beth47@gmail.com",
                            Nombre = "Beth"
                        },
                        new
                        {
                            ProfesorId = 9,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rau",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "in",
                            Email = "Greg13@gmail.com",
                            Nombre = "Greg"
                        },
                        new
                        {
                            ProfesorId = 10,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kub",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "in",
                            Email = "Nettie_Kub@hotmail.com",
                            Nombre = "Nettie"
                        },
                        new
                        {
                            ProfesorId = 11,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schuster",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "ut",
                            Email = "Tracy.Schuster11@gmail.com",
                            Nombre = "Tracy"
                        },
                        new
                        {
                            ProfesorId = 12,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Prosacco",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "sint",
                            Email = "Lionel_Prosacco28@yahoo.com",
                            Nombre = "Lionel"
                        },
                        new
                        {
                            ProfesorId = 13,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Mertz",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "deleniti",
                            Email = "Delbert_Mertz14@gmail.com",
                            Nombre = "Delbert"
                        },
                        new
                        {
                            ProfesorId = 14,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lesch",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "tenetur",
                            Email = "Derek.Lesch71@hotmail.com",
                            Nombre = "Derek"
                        },
                        new
                        {
                            ProfesorId = 15,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lind",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "dolorem",
                            Email = "Ashley44@hotmail.com",
                            Nombre = "Ashley"
                        },
                        new
                        {
                            ProfesorId = 16,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Willms",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "illum",
                            Email = "Cindy_Willms83@yahoo.com",
                            Nombre = "Cindy"
                        },
                        new
                        {
                            ProfesorId = 17,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hauck",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "laudantium",
                            Email = "Florence.Hauck70@hotmail.com",
                            Nombre = "Florence"
                        },
                        new
                        {
                            ProfesorId = 18,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schmidt",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "animi",
                            Email = "Bryant.Schmidt34@yahoo.com",
                            Nombre = "Bryant"
                        },
                        new
                        {
                            ProfesorId = 19,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Gorczany",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "a",
                            Email = "Cora_Gorczany55@gmail.com",
                            Nombre = "Cora"
                        },
                        new
                        {
                            ProfesorId = 20,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Grady",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "non",
                            Email = "Roland_Grady52@gmail.com",
                            Nombre = "Roland"
                        },
                        new
                        {
                            ProfesorId = 21,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Braun",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "quisquam",
                            Email = "Stacy_Braun@gmail.com",
                            Nombre = "Stacy"
                        },
                        new
                        {
                            ProfesorId = 22,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Satterfield",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "voluptatem",
                            Email = "Verna_Satterfield88@yahoo.com",
                            Nombre = "Verna"
                        },
                        new
                        {
                            ProfesorId = 23,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Auer",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "molestias",
                            Email = "Sammy29@gmail.com",
                            Nombre = "Sammy"
                        },
                        new
                        {
                            ProfesorId = 24,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rutherford",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "hic",
                            Email = "Kim41@hotmail.com",
                            Nombre = "Kim"
                        },
                        new
                        {
                            ProfesorId = 25,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Rice",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "rerum",
                            Email = "Patrick65@hotmail.com",
                            Nombre = "Patrick"
                        },
                        new
                        {
                            ProfesorId = 26,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schroeder",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "id",
                            Email = "Ricardo.Schroeder@yahoo.com",
                            Nombre = "Ricardo"
                        },
                        new
                        {
                            ProfesorId = 27,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Mayer",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "sed",
                            Email = "Angelo.Mayer55@gmail.com",
                            Nombre = "Angelo"
                        },
                        new
                        {
                            ProfesorId = 28,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Fritsch",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "est",
                            Email = "Maxine43@gmail.com",
                            Nombre = "Maxine"
                        },
                        new
                        {
                            ProfesorId = 29,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hammes",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "beatae",
                            Email = "Brittany57@gmail.com",
                            Nombre = "Brittany"
                        },
                        new
                        {
                            ProfesorId = 30,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Kub",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "neque",
                            Email = "Beverly_Kub@hotmail.com",
                            Nombre = "Beverly"
                        },
                        new
                        {
                            ProfesorId = 31,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Dickens",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "incidunt",
                            Email = "Santos.Dickens@yahoo.com",
                            Nombre = "Santos"
                        },
                        new
                        {
                            ProfesorId = 32,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Cole",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "eaque",
                            Email = "Alfred_Cole@hotmail.com",
                            Nombre = "Alfred"
                        },
                        new
                        {
                            ProfesorId = 33,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Mills",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "iusto",
                            Email = "Lillian.Mills16@hotmail.com",
                            Nombre = "Lillian"
                        },
                        new
                        {
                            ProfesorId = 34,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Runolfsson",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "saepe",
                            Email = "Melanie.Runolfsson3@gmail.com",
                            Nombre = "Melanie"
                        },
                        new
                        {
                            ProfesorId = 35,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wilderman",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "deserunt",
                            Email = "Brandon.Wilderman67@hotmail.com",
                            Nombre = "Brandon"
                        },
                        new
                        {
                            ProfesorId = 36,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wintheiser",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "sed",
                            Email = "Shawn58@gmail.com",
                            Nombre = "Shawn"
                        },
                        new
                        {
                            ProfesorId = 37,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Koch",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "rerum",
                            Email = "Christopher14@gmail.com",
                            Nombre = "Christopher"
                        },
                        new
                        {
                            ProfesorId = 38,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Zemlak",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "alias",
                            Email = "Paula_Zemlak78@gmail.com",
                            Nombre = "Paula"
                        },
                        new
                        {
                            ProfesorId = 39,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Lang",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "quidem",
                            Email = "Amanda_Lang@hotmail.com",
                            Nombre = "Amanda"
                        },
                        new
                        {
                            ProfesorId = 40,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Schimmel",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "at",
                            Email = "Fred_Schimmel52@gmail.com",
                            Nombre = "Fred"
                        },
                        new
                        {
                            ProfesorId = 41,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Hoppe",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "cumque",
                            Email = "Kenny_Hoppe@yahoo.com",
                            Nombre = "Kenny"
                        },
                        new
                        {
                            ProfesorId = 42,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Daniel",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "tempore",
                            Email = "Herbert_Daniel78@yahoo.com",
                            Nombre = "Herbert"
                        },
                        new
                        {
                            ProfesorId = 43,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Herman",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "aperiam",
                            Email = "Curtis.Herman34@yahoo.com",
                            Nombre = "Curtis"
                        },
                        new
                        {
                            ProfesorId = 44,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Little",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "sed",
                            Email = "Earnest.Little@gmail.com",
                            Nombre = "Earnest"
                        },
                        new
                        {
                            ProfesorId = 45,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Little",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "alias",
                            Email = "Gina_Little@yahoo.com",
                            Nombre = "Gina"
                        },
                        new
                        {
                            ProfesorId = 46,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Robel",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "officia",
                            Email = "Amanda.Robel67@hotmail.com",
                            Nombre = "Amanda"
                        },
                        new
                        {
                            ProfesorId = 47,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Pacocha",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "fugit",
                            Email = "Tonya95@yahoo.com",
                            Nombre = "Tonya"
                        },
                        new
                        {
                            ProfesorId = 48,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Bailey",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "fuga",
                            Email = "Celia.Bailey39@hotmail.com",
                            Nombre = "Celia"
                        },
                        new
                        {
                            ProfesorId = 49,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Morar",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "modi",
                            Email = "Lyle_Morar73@yahoo.com",
                            Nombre = "Lyle"
                        },
                        new
                        {
                            ProfesorId = 50,
                            Actualizado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Apellido = "Wolff",
                            Creado = new DateTime(2024, 11, 21, 10, 7, 16, 575, DateTimeKind.Local).AddTicks(2515),
                            CreadoPor = "MinHacienda",
                            Departamento = "et",
                            Email = "Morris.Wolff@yahoo.com",
                            Nombre = "Morris"
                        });
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Asignacion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("MinHaciendaDomain.Models.Inscripcion", b =>
                {
                    b.HasOne("MinHaciendaDomain.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinHaciendaDomain.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
